import {
  birb,
  braniac_fish,
  card_back,
  electrified_guin_piggo,
  ferret,
  flying_pug,
  glam_dog,
  guinea_pig,
  hungry_hamster,
  irritable_kitty,
  bearded_dragon,
  scaredy_cat,
  smart_doggo,
  tarantula,
  tiger_king,
  wise_old_monkey,
} from "./pictures";

export const cardBack = {
  id: "cardBack",
  image: card_back,
};

export const importedCards = [
  {
    id: "birb",
    name: "Birb",
    image: birb,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "braniac_fish",
    name: "Braniac Fish",
    image: braniac_fish,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "electrified_guin_piggo",
    name: "Static Guin Piggo",
    image: electrified_guin_piggo,
    hp: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "ferret",
    name: "Ferret",
    image: ferret,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "flying_pug",
    name: "Flying Pug",
    image: flying_pug,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "glam_dog",
    name: "Glam Dog",
    image: glam_dog,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "guinea_pig",
    name: "Guinea Pig",
    image: guinea_pig,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "hungry_hamster",
    name: "Hungry Hamster",
    image: hungry_hamster,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "irritable_kitty",
    name: "Irritable Kitty",
    image: irritable_kitty,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "bearded_dragon",
    name: "Bearded Dragon",
    image: bearded_dragon,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "scaredy_cat",
    name: "Scaredy Cat",
    image: scaredy_cat,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "smart_doggo",
    name: "Smart Doggo",
    image: smart_doggo,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "tarantula",
    name: "Tarantula",
    image: tarantula,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "tiger_king",
    name: "Tiger King",
    image: tiger_king,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
  {
    id: "wise_old_monkey",
    name: "Wise Old Monkey",
    image: wise_old_monkey,
    hp: 100,
    rarity: 100,
    attack1: {
      name: "attack one",
      dmg: 10,
      details: null,
    },
    attack2: {
      name: "attack two",
      dmg: 30,
      details: "Flip a coin. If tails, does 10 damge to itself",
    },
  },
];
