import {
  birb,
  braniac_fish,
  card_back,
  electrified_guin_piggo,
  ferret,
  flying_pug,
  glam_dog,
  guinea_pig,
  hungry_hamster,
  irritable_kitty,
  komodo_dragon,
  scaredy_cat,
  smart_doggo,
  tarantula,
  iger_king,
  wise_old_monkey,
} from "./pictures";
